"use client";

import React from "react";
import { ItineraryWithRelations } from "../../types/itineraryTypes";

const Footer = ({ itinerary }: { itinerary: ItineraryWithRelations }) => {
  return (
    <footer className="mt-12 text-gray-600 text-center">
      <p>Generated by AI for {itinerary.destination}</p>
    </footer>
  );
};

export default Footer;
